### ISSUE TITLE
Definition of Model ID for use with pyPESTO and AMICI

### ISSUE THREAD

**Issue by elbaraim** [yaml2sbml-dev/yaml2sbml#101]
Currently when a new model is created after using this wonderful tool the model field read as
`<model>`

This leads (when used together with pyPESTO and AMICI) to the generation of a random name which is used as name for the model in the amici folder, e.g. `amici_models/tmpiouv7fa5`.
The problem here is that every time one will load the model, the random name is changing, therefore the already compiled folder is not detected, and the model is compiled again.

This has a very simple fix. During the model creation you can add the model ID, such that the final sbml model will contain
`<model id="MyModelName" name="MyModelName">`
instead of
`<model>`

I do not know how this behaves for other tools, but for pyPESTO/AMICI this would be a valuable fix.

**Comment by yannikschaelte** [comment]
I agree that filling the model id consistently into the various places it's used (in the sbml, as folder names etc) is a good idea. Currently, the model has no id, so this should be easy to fix.

**Comment by jvanhoefer** [comment]
similarly it would be great, if the  model name is somehow reflected in the created PEtab tables of `yaml2petab`. So let's go for

`observables_<model_name>.tsv` instead of `observable_table.tsv` as currently...

**Comment by jvanhoefer** [comment]
So, all of that is done, only this breaks the tests, that compare the result of SBML conversion to a precomputed SBML...
