### ISSUE TITLE
Logo not rendering on README

### ISSUE THREAD

**Issue by martamatos** [yaml2sbml-dev/yaml2sbml#102]
In the develop branch:
![image](https://user-images.githubusercontent.com/609864/107877009-eb4b6200-6ec9-11eb-88a1-3ce8764c2d3a.png)

Shouldn't the logo be rendering there?

**Comment by yannikschaelte** [comment]
It's a fully qualified link targeting the master branch, bc otherwise it would not show on pypi. It should show everywhere once it's merged to the main branch.

**Comment by yannikschaelte** [comment]
Oh, but @martamatos there is indeed a problem: The link should contain /main/, not /master/.

**Comment by martamatos** [comment]
It still seems smart enough to go to main automatically: https://github.com/yaml2sbml-dev/yaml2sbml/blob/main/doc/logo/logo_yaml2sbml_long.png
Is the 404 error expected though?

**Comment by yannikschaelte** [comment]
Ah good, then it should in principle work. Yes, the 404 is expected until develop is merged into main.
