### ISSUE TITLE
Use petablinter in example notebooks to demonstrate that the output is valid PEtab

### ISSUE THREAD

**Issue by yannikschaelte** [yaml2sbml-dev/yaml2sbml#106]
Inserting a cell `!petablint -v -y $petab_yaml_file` (currently does not have a real python API).

**Comment by jvanhoefer** [comment]
actually, inside of of the `validate_petab_tables` function, the PEtab linter does exactly this

https://github.com/yaml2sbml-dev/yaml2sbml/blob/a8abacbb3a66eac4d92ed615a365c79e7aa56431/yaml2sbml/yaml2PEtab.py#L259

And this function again is called after every `yaml2petab` call...

Doesn't this resolve the problem? :)

**Comment by jvanhoefer** [comment]
here it is called inside `yaml2petab`
https://github.com/yaml2sbml-dev/yaml2sbml/blob/a8abacbb3a66eac4d92ed615a365c79e7aa56431/yaml2sbml/yaml2PEtab.py#L114

Hence the user is informed, if the linter complains about the resulting PEtab problem

**Comment by yannikschaelte** [comment]
That's good! I was just wondering whether one wants to also explicitly have it in the notebooks to show to the user that all works, as the user may not know that all functions were internally already called.
