### ISSUE TITLE
Reviewer comments for JOSS submisson

### ISSUE THREAD

**Issue by SirSharpest** [yaml2sbml-dev/yaml2sbml#125]
Hi, 

I'll be making any comments, suggestions or issue I run into here, to keep the main review page less-cluttered. This is in relation to the main review page here: https://github.com/openjournals/joss-reviews/issues/3215

I'll be making comments as I come across them in the next few days (apologies for any delay, I am currently travelling). 

Thanks for your submission, and I look forward to reviewing this submission. 

Best,
Nathan

**Comment by SirSharpest** [comment]
I'd like to start by saying that the quality of this repo is excellent. Documentation is great, for example when I wanted to find information on running tests I found it to be perfectly explained. 

Some minor thoughts: 

- The MIT license names two authors and not all authors named on the paper. Is this intentional, if so, disregard this comment. 
-  Your examples have some extra dependencies, I recognize that these are configurable in the setup file, but I could not find mention of the specific ```pip command```  in the docs to run to get example notebooks to run quickly. 
- I ran into some issues with the amici library installing on my OSX machine https://amici.readthedocs.io/en/v0.11.12/python_installation.html - there are some additional dependencies, possibly worth flagging as other users may come across this when doing a clean installation?
    - I recognise this is not an issue of your software, but just may create a barrier for users who may quit trying to use the package after a wall of errors

**Comment by jvanhoefer** [comment]
Hey Nathan, 

first of all: Thank you a lot for your positive and constructive feedback! I will address your comments in the branch `feature_JOSS_review_comments`. 

Regarding AMICI: You are right, AMICI can have some issues during installation and it will be helpful to offer some guidance for installing AMICI already in the docs of yaml2sbml. 

Did you get AMICI running in the end? (AMICI is also developed in our group, therefore if you have any questions regarding that: We are happy to help :) )

**Comment by SirSharpest** [comment]
Yeah, I did, thanks. 

As I said, it was very difficult to find any improvements which could be made. I'm confident that this is ready for publication.

**Comment by jvanhoefer** [comment]
Happy to hear your feedback and thank you for taking the time to review our submission and code!
