### ISSUE TITLE
improve import syntax

### ISSUE THREAD

**Issue by jvanhoefer** [yaml2sbml-dev/yaml2sbml#23]
Currently, the standard syntax for importing and calling yaml2sbml is

```python
import yaml2sbml 

yaml2sbml.yaml2sbml.yaml2sbml(input_file, output_file)
yaml2sbml.yaml2sbml.yaml2PEtab(...)
```
(Since there the package `yaml2sbml` contains a folder `yaml2sbml`, that contains the function `yaml2sbml`)

I would argue, that we would want, to change that to `yaml2sbml.yaml2sbml(input_file, output_file)` and `yaml2sbml.yaml2PEtab(...)`.

**Comment by jvanhoefer** [comment]
Probably, this could be changed by adding a `__init__`? Would have to have a look :)

**Comment by yannikschaelte** [comment]
Exactly. `echo "from .yaml2sbml import yaml2sbml" >> __init__.py`, same for petab ;)
