### ISSUE TITLE
Move examples from examples repo to here

### ISSUE THREAD

**Issue by jvanhoefer** [yaml2sbml-dev/yaml2sbml#33]
There is the (private) yaml2sbml repo. Jan suggested, to move this in the examples repo of yaml2sbml, instead of having two separate locations for that. (I would replace the current examples by that).

**Comment by jvanhoefer** [comment]
@martamatos Opinions?

**Comment by martamatos** [comment]
I'm a bit lost :/ 
Which yaml2sbml private repo?
And if i got it right, that private repo would be moved to the examples repo?

**Comment by jvanhoefer** [comment]
This repo has an examples folder, that contains a really old/"historic" `yaml` file (where I do not even know, if it still is valid, since it has e.g. the `events` keyword, that never got realized).

Therefore I would suggest to replace this by the `yaml2sbml-dev/yaml2sbml_examples` repo, that is currently private, but you should have access to that via this github-organization :)

**Comment by martamatos** [comment]
Ahah! Yeah, that example looks old indeed :)
And yes, i agree with replacing that folder by the repo `yaml2sbml-dev/yaml2sbml_examples` :)
