### ISSUE TITLE
Add Notebooks to test

### ISSUE THREAD

**Issue by jvanhoefer** [yaml2sbml-dev/yaml2sbml#34]
After finishing #33, I would like to add the notebooks as unit tests (is done for e.g. pypesto)... :)

**Comment by martamatos** [comment]
As automatic unit tests or as "integration" tests where you do some stuff and make sure (manually) that it all went well?

**Comment by yannikschaelte** [comment]
Suggesting automatic, as in https://github.com/ICB-DCM/pyPESTO/blob/master/test/run_notebook.sh

**Comment by martamatos** [comment]
Ah! Nice :) 
And basically if the notebooks run without errors it's all good, is that it? Or are there any other situations in which the test can fail?

**Comment by yannikschaelte** [comment]
This just tests that all notebooks run without programmatic errors (as in: If a user runs a notebook, and it fails, that's bad, so better check it in CI).

Whether code changes introduced any conceptual errors letting the notebooks pass but their output just nonsense, this does not check, therefore one needs unit tests.

**Comment by martamatos** [comment]
Yes, that makes perfect sense, thank you for the explanation :)

**Comment by alex-treebeard** [comment]
hey folks, I just released [nbmake](https://github.com/treebeardtech/nbmake) and would be interested to know if it could help you here?

**Comment by jvanhoefer** [comment]
Hey Alex, thank you for your message! This is definitely interesting and I will have a look for it. (Will have to finish the notebooks first  though...).  I will keep you updated :)
