### ISSUE TITLE
Move tests to github actions

### ISSUE THREAD

**Issue by yannikschaelte** [yaml2sbml-dev/yaml2sbml#53]
The computation budget on travis will soon run out.

**Comment by jvanhoefer** [comment]
jep, and trying how to install amici there by running a lot of tests does not help either... -.-

**Comment by jvanhoefer** [comment]
What's the standard strategy for moving to GitHub actions?

**Comment by yannikschaelte** [comment]
I think there is no automatic moving, one needs to set up a new yml script. I can shortly do that (and also install AMICI there :unicorn: ) if you like.

**Comment by jvanhoefer** [comment]
That would be great ☺️

**Comment by yannikschaelte** [comment]
Please find suggestions in https://github.com/yaml2sbml-dev/yaml2sbml/pull/54.

**Comment by yannikschaelte** [comment]
See typical runs e.g. here: https://github.com/yannikschaelte/yaml2sbml/actions/runs/488473228
