### ISSUE TITLE
deploy to pypi

### ISSUE THREAD

**Issue by jvanhoefer** [yaml2sbml-dev/yaml2sbml#59]
@martamatos I will do this, after #55 and #56 are merged. (Probably via github actions, we will see :) )

**Comment by yannikschaelte** [comment]
Maybe do an 0.0.0a1 release manually soon, just to reserve the name. See [here](https://pyabc.readthedocs.io/en/latest/deploy.html#upload-to-the-python-package-index-pypi) for a howto, or [here](https://github.com/PEtab-dev/PEtab/blob/develop/.github/workflows/deploy.yml) for how to correctly use GHA (in addition one needs to upload the secret password to github).

**Comment by jvanhoefer** [comment]
🚀 @martamatos it is on pip now :)

**Comment by martamatos** [comment]
:D
