### ISSUE TITLE
Documentation on readthedocs

### ISSUE THREAD

**Issue by yannikschaelte** [yaml2sbml-dev/yaml2sbml#60]
If it is intended to host nicely readable docs on readthedocs.io (I suggest to do so):
* [x] Register the project there
* [x] Set up CI
* [x] Set up automatic testing of docs build for PRs

**Comment by martamatos** [comment]
I've been slow as a snail, but i've set up a draft here: https://yaml2sbml.readthedocs.io/en/latest/
Still need to figure out how to add more people (thought I had added @jvanhoefer, but nop).

**Comment by yannikschaelte** [comment]
Nice! Adding maintainers: readthedocs.org -> project -> Admin -> Maintainers -> Add maintainer. My name would be yannik.schaelte ;)

**Comment by martamatos** [comment]
I think I just added you, did you get anything?

**Comment by yannikschaelte** [comment]
No notification yet, but yes, I can see it in my list of projects now!

**Comment by yannikschaelte** [comment]
all done, as far as I can see
