### ISSUE TITLE
Remove Codacy again?

### ISSUE THREAD

**Issue by jvanhoefer** [yaml2sbml-dev/yaml2sbml#65]
@martamatos @dilpath @yannikschaelte 

Seeing, that all current PRs fail not due to failed tests but due to Codacy complaining about weird markdown/doc string issues (where I even don't get all changes, that I would have to do, to make Codacy happy)...: I would propose to get rid of Codacy again. 

We have flake8, that should be sufficient for the moment?

**Comment by yannikschaelte** [comment]
Totally fine to skip codacy. Alternative would be to configure in a yml file what it should actually check. Many things it brings up make sense, but you have better control if you install further flake8 packages (i.g. bugbear), than with codacy. So, if the fancy badge does not matter, just drop it.

**Comment by martamatos** [comment]
I agree with Yannik :)

**Comment by jvanhoefer** [comment]
Right it seems as coadcy stays :D Also most issues were resolved...
