### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by yannikschaelte** [yaml2sbml-dev/yaml2sbml#69]
Would enhance recognizability a lot :heart_eyes:

**Comment by yannikschaelte** [comment]
After discussion with @jvanhoefer , here is a first draft. Opinions welcome :laughing: The colors are the original yaml and sbml logo colors.

![image](https://user-images.githubusercontent.com/31767307/106300367-ba76f600-6256-11eb-8094-25c5df064fbf.png)

**Comment by jvanhoefer** [comment]
@martamatos @dilpath How do you like yanniks winky face...? :)

**Comment by martamatos** [comment]
Took me a bit to recognize the winky face, but now that i see it i think it's pretty cool :D
Any chance i could play with the original?

**Comment by yannikschaelte** [comment]
Yes! I just sent it to you via mail, as I could not upload it here directly. If everyone only recognizes the face after being told there is one, this should be improved :laughing:

**Comment by dilpath** [comment]
Looks good! Winkier wink?

![logo_yaml2sbml_inkscape_wink](https://user-images.githubusercontent.com/59329744/106306261-142eee80-625e-11eb-835c-dfc6752c3639.png)


[logo_yaml2sbml_inkscape_wink.zip](https://github.com/yaml2sbml-dev/yaml2sbml/files/5895223/logo_yaml2sbml_inkscape_wink.zip)

**Comment by jvanhoefer** [comment]
What I liked about yanniks slighter wink, was that the left part still reminded more off the typical optics of a yaml file... :)

**Comment by martamatos** [comment]
I was playing a little, here's the result:

![image](https://user-images.githubusercontent.com/609864/106330567-5d416b80-627b-11eb-87b2-4ef10d507d2f.png)

I also prefer the less winky one btw.

**Comment by yannikschaelte** [comment]
All nice! If we want to use this general concept, maybe we can try to go for some in-between winkiness.

**Comment by jvanhoefer** [comment]
In general to me this is a trade off between winkiness and yaml-ness :D So maybe since currently the discussion is "did you get the wink at first sight" let's ask the opposite question: "Did you get the left eye looks like yaml file reference?"

**Comment by dilpath** [comment]
The reference was clear, but it might be better to ask people that are less involved in the project.

**Comment by jvanhoefer** [comment]
I tried around a bit and had only one minor detail, that I was disliking: The "lowest of the three YAML-lines" was not starting at the same indentation level, as the one above. So with this super minor adjustment: This would be my proposal. I will try to get some feedback from our group and if no one of you is shouting "NOOOO", I could do a PR with it some where soon :) (assuming that all of you like the general idea of the Logo... :) ) 
[logo_yaml2sbml_inkscape_wink_jv.svg.zip](https://github.com/yaml2sbml-dev/yaml2sbml/files/5910814/logo_yaml2sbml_inkscape_wink_jv.svg.zip)

**Comment by yannikschaelte** [comment]
Looks good to me! Yes, let's do a customer product testing / review :).

**Comment by yannikschaelte** [comment]
As usual, I suggest then 2 logos: Once only the symbol (quadratic, as icon), and once with the text next to it, same height as symbol.

**Comment by dilpath** [comment]
Looks good to me! Looks like the center of the eyes do not align with the center of the mouth (maybe the center of the eyes are aligned to the center of the mouth+arrow head currently?).

**Comment by jvanhoefer** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/38346459/106632447-0b039180-657e-11eb-9cf4-6c8ccedf30b8.png">

In order to have a complimentary approach: Here a second logo, that does not have an arrow that makes people think of an American delivery company...

**Comment by martamatos** [comment]
woW! That one is pretty cool :D
I'd vote for the rocket xD

**Comment by yannikschaelte** [comment]
I also like it. Minor fixes: even spacing between red and grey, and maybe blue above grey.
And I don't know any companies with rocket symbol ;)

**Comment by jvanhoefer** [comment]
> I also like it. Minor fixes: even spacing between red and grey, and maybe blue above grey.

I just sent you the .svg file

**Comment by yannikschaelte** [comment]
I have uploaded 3 variants (long, short, icon) in https://github.com/yaml2sbml-dev/yaml2sbml/tree/feature_logo/doc/logo. How do these look?
