### ISSUE TITLE
unify requirements.txt and setup.py

### ISSUE THREAD

**Issue by jvanhoefer** [yaml2sbml-dev/yaml2sbml#72]
We have both, and there are different things written in there/different versions specified in there. Should change that! (only setup.py?)

**Comment by yannikschaelte** [comment]
pep8-wise, both is fine, but having all in setup.py would be easier, as then all requirements are in one place. I would further say (probably done already), having >=minimum_version for each dependency.

**Comment by yannikschaelte** [comment]
done and in master
