### ISSUE TITLE
Tidy up Docs/Deploy

### ISSUE THREAD

**Issue by jvanhoefer** [yaml2sbml-dev/yaml2sbml#77]
Some things still in the ToDo

- [x] Automatically update readthedocs when merging into master
- [x] Same for pypi
- [ ] Restructure docs: Own Folder for all sphinx stuff, since this is distracting from examples, releasnotes & format docs, which in some sense is the important stuff...

**Comment by jvanhoefer** [comment]
@yannikschaelte I assigned you, since at least for the first two things you offered to do these... :)

**Comment by yannikschaelte** [comment]
pypi see #80. Deployment to readthedocs should already be automatically happening as there exists a webhook (master+develop), I think.

**Comment by yannikschaelte** [comment]
FYI: I have enabled readthedocs for both [master](https://yaml2sbml.readthedocs.io) and [develop](https://yaml2sbml.readthedocs.io/en/develop/) branch. Thus, one can directly check how the docs look on develop branch already. If you want, you can also register your mail address on readthedocs.io under Notifications to get a notification of failed builds.

**Comment by yannikschaelte** [comment]
yaml2sbml.rtfd.io should target master, not develop. If that has not changed in a few minutes, some setting is still wrong.

**Comment by jvanhoefer** [comment]
Since we won't go for an own folder for sphinx, this is closed, right?

**Comment by yannikschaelte** [comment]
Sorry @jvanhoefer , I missed this. Yes, I would say it is fine -- the doc/ folder should be sufficiently tidied up now.
