### ISSUE TITLE
check if input yaml has a valid format...

### ISSUE THREAD

**Issue by jvanhoefer** [yaml2sbml-dev/yaml2sbml#8]
similarly to PEtab, see

https://github.com/PEtab-dev/PEtab/blob/master/petab/petab_schema.yaml

**Comment by martamatos** [comment]
To avoid double work, I am currently working on this :)

**Comment by jvanhoefer** [comment]
Hey, 
this is the schema for the PEtab format,
https://github.com/PEtab-dev/PEtab/blob/master/petab/petab_schema.yaml

**Comment by jvanhoefer** [comment]
validation is then done here afaik
https://github.com/PEtab-dev/PEtab/blob/master/petab/yaml.py

**Comment by martamatos** [comment]
Thank you! I've already adapted the validation function to our case, now i just need to sit on the computer for a bit and make sure it all works fine :)
