### ISSUE TITLE
Logo background

### ISSUE THREAD

**Issue by jvanhoefer** [yaml2sbml-dev/yaml2sbml#84]
I just changed the logo of the organization to our rocket (somehow not always shown...).

 Is for you the background of the square also dark grey, or is this only due to me dark theme in GitHub (looks ugly tbh, maybe we should think of using a version, that has a white background, if these kinds of problems happen more frequent...)

**Comment by jvanhoefer** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/38346459/106819426-120fca00-667a-11eb-9ca8-b5e530d3bfd4.png">
Here is proof

**Comment by jvanhoefer** [comment]
Might also be the colorblind me, who doesn't like the grey-in-grey...

**Comment by dilpath** [comment]
Seems to be in the GitHub style sheets to set the background of logos to this grey colour. Blends in a bit at smaller sizes especially, to me. Could be made more visible by adding a small stroke to the rocket (and possibly the red/blue parts). 

Can see that this is not an issue in general for the logo, in the README (currently can only be viewed on a PR branch)
https://github.com/yaml2sbml-dev/yaml2sbml/tree/fix_logo_link

**Comment by yannikschaelte** [comment]
I find all logos to look bad in GitHub dark mode as it adds that grey background even if the logo would be compatible wit black as in our case. I think the only solution would be to use a alpha != 0 white background, but I kind of prefer the no-background.

**Comment by jvanhoefer** [comment]
fine with that. having a white block around es not to nice on the dark mode either...
