### ISSUE TITLE
Rename master -> main?

### ISSUE THREAD

**Issue by yannikschaelte** [yaml2sbml-dev/yaml2sbml#86]
For given reasons, GitHub encourages to rename the master branch to main https://github.com/github/renaming. Should we do that? Renaming works automated, one would only need to check whether we use the word "master" e.g. in the docs.

**Comment by martamatos** [comment]
I don't see why not :)

**Comment by yannikschaelte** [comment]
Ok, then I will do this in an hour or so. Readthedocs should require not updates (:crossed_fingers:), the doc/contribute.rst needs to be updated, will do that then, hope the other integrations work fine.

**Comment by yannikschaelte** [comment]
Done. Docs TBD.
