### ISSUE TITLE
Tidy up outputs of notebooks

### ISSUE THREAD

**Issue by yannikschaelte** [yaml2sbml-dev/yaml2sbml#89]
Currently, the notebooks seem to generate outputs in different subfolders, which makes the .gitignore quite complex ... May be good to find a common structure there.

**Comment by jvanhoefer** [comment]
I do only see one thing, that could be done here: All the compiled AMICI models in `tempfiles`. 

Besides, there are only the yaml/sbml models, that are generated, when running the examples. I think, it is reasonable, that they are _not_ on GitHub, but only are generated when running the notebooks locally, but _also_ think, that it is nice to be able to view them after running  the examples and having them inside of the folder of the example itself.

**Comment by yannikschaelte** [comment]
Agreed! Can one somehow go by extension? xml/yaml? Otherwise one should manually run all notebooks and add all files to .gitignore that should not be in the repo.

**Comment by yannikschaelte** [comment]
Alternatively, one could put all outputs inside an "output" subfolder of the repositories, which simplifies cleaning up, but may be not so nice tutorial-wise, I did not look into that.

**Comment by jvanhoefer** [comment]
Nope, at least not for .yaml. Some notebooks only modify existing models.

The most annoying part are the PEtab models, but there as well: The measurement table needs to be respecified, hence you need to manually select which folders to delete.

**Comment by jvanhoefer** [comment]
There are even points, where all files belonging to an extension are deleted in the .gitignore (where this is possible). But unfortunately, there should be no additional easy improvement, that is not harmful "didactically"
