### ISSUE TITLE
Notebooks fail

### ISSUE THREAD

**Issue by yannikschaelte** [yaml2sbml-dev/yaml2sbml#90]
Some (3-4) of the notebooks fail when run with `pytest --nbmake doc/examples`.

**Comment by jvanhoefer** [comment]
which ones fail?

**Comment by yannikschaelte** [comment]
The 3 "F"s:

```sh
doc/examples/Finite_State_Projection/Finite_State_Projection.ipynb .                           [ 16%]
doc/examples/Format_Features/Format_Features.ipynb F                                              [ 33%]
doc/examples/Lotka_Volterra/Lotka_Volterra_CLI/Lotka_Volterra_CLI.ipy.                      [ 50%]
doc/examples/Lotka_Volterra/Lotka_Volterra_Model_Editor/Lotka_Volterra_Model_Editor.ipynb F    [ 66%]
doc/examples/Lotka_Volterra/Lotka_Volterra_python/Lotka_Volterra.ipynb .                       [ 83%]
doc/examples/Sorensen/yaml2sbml_Sorensen.ipynb F                                               [100%]
```

**Comment by jvanhoefer** [comment]
@dilpath : You just fixed two, the `Format_Features.ipynb` is still open,  right?

**Comment by dilpath** [comment]
> @dilpath : You just fixed two, the `Format_Features.ipynb` is still open, right?

Correct, there is a partial fix in an [AMICI PR](https://github.com/AMICI-dev/AMICI/pull/1404) but that currently leads to additional errors, and may take time to resolve. It is related to the use of a piecewise function in the notebook.
