### ISSUE TITLE
validation error for formulas starting with minus

### ISSUE THREAD

**Issue by jvanhoefer** [yaml2sbml-dev/yaml2sbml#99]
As @yannikschaelte pointed out to me: If a right hand side/formula starts with a minus, the translator/validator throws  `ScannerError: sequence entries are not allowed here` (Since yaml-blocks start with a `-`, and the validator complains...). I don't know, wether there is a direct fix (but doubt this a bit, since this is how yaml are parsed??). 

Possible ways around would be setting the formula either in quotes ("...") or in brackets... Therefore I propose

- [x] Explaining this in Format Docs & evtl. README (known issues)
- [x] catching the `ScannerError` and throw a meaningfull error there 
- [x] Test, if the Model Editor works in this case?

**Comment by jvanhoefer** [comment]
Other points in a similar direction

- [ ] specify, that any id needs to be a valid SBML identifier (and what that means...)
- [ ] any formula is parsed by libsbmls math parser (and what that means), currently that's the last point of the format docu. Make this better visible!

**Comment by yannikschaelte** [comment]
One could reference the sbml [specification](http://sbml.org/Documents/Specifications#SBML_Level_3), but there may also be constraints from [libsbml](http://model.caltech.edu/software/libsbml/5.18.0/docs/formatted/python-api/libsbml-math.html) or mathml, so eventually only the successful export to sbml may give full validity.
